# Generated by Django 5.2.8 on 2026-01-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
